# -*- coding: utf-8 -*-
"""Big DATA-LLMs-NPCR-One Fold.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XFghNqZHLL-JyqoWy_m1xDeb20aOMdvz

**Installing Required Libraries**
"""

!pip install torch==1.13.1 torchvision==0.14.1 torchaudio==0.13.1
!pip install transformers==4.41.0
import torch
!pip install numpy pandas

"""**Data Loading and Preparation**

"""

import os

# Base path for folder
base_path = "/content/drive/MyDrive/Big Data/LLMs in Education/Autho Scoring Essay-NPCR Model/data-set/asap"
preprocess_script = "/content/drive/MyDrive/Big Data/LLMs in Education/Autho Scoring Essay-NPCR Model/data-set/asap/preprocess_asap.py"

# Path for a single fold (fold_1)
fold_path = os.path.join(base_path, "fold_1")

# Input files for the single fold
for data_type in ['test', 'train', 'dev']:
    data_file = os.path.join(fold_path, f"{data_type}.tsv")
    ids_file = os.path.join(fold_path, f"{data_type}_ids.txt")

    print(f"Processing {data_file} with IDs from {ids_file}")
    os.system(f'python "{preprocess_script}" -i "{data_file}" -id "{ids_file}"')

"""**Main Running**"""

import nltk
nltk.download('punkt_tab')

import nltk
nltk.data.path.append('/root/nltk_data')

from nltk.tokenize import word_tokenize
text = "Hello, this is a test sentence for tokenization."
tokens = word_tokenize(text)
print(tokens)

!python "/content/drive/MyDrive/Big Data/LLMs in Education/Autho Scoring Essay-NPCR Model/aes-neural-pairwise-contrastive-regression/main.py" --oov random --checkpoint_path "/content/drive/MyDrive/Big Data/LLMs in Education/Autho Scoring Essay-NPCR Model/checkpoint" --train "/content/drive/MyDrive/Big Data/LLMs in Education/Autho Scoring Essay-NPCR Model/data-set/asap/fold_1/train.tsv" --dev "/content/drive/MyDrive/Big Data/LLMs in Education/Autho Scoring Essay-NPCR Model/data-set/asap/fold_1/dev.tsv" --test "/content/drive/MyDrive/Big Data/LLMs in Education/Autho Scoring Essay-NPCR Model/data-set/asap/fold_1/test.tsv"